services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000"  # Esponi la porta del backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nome_database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
